cart/urls.py
# @时间 2024/7/30 15:36
# @Author：郑摇2021210510
# @File : urls.py

from django.urls import path

from cart import views

urlpatterns = [
    path('addCart/', views.AddCartView.as_view()),
    path('cartList/', views.CartListView.as_view()),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('goods.urls')),
    path('users/', include('usersapp.urls')),
    path('cart/', include('cart.urls')),
    path('trend/', include('trend.urls')),
    path('order/', include('order.urls')),
    path('forum/', include('forum.urls')),
    path('evaluate/', include('evaluate.urls'))
]

usersapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' orders
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class Area(models.Model):
    areaid = models.IntegerField(primary_key=True)
    areaname = models.CharField(max_length=50)
    parentid = models.IntegerField()
    arealevel = models.IntegerField()
    status = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'area'
class UserInfo(models.Model):
    uname = models.CharField(max_length=100)
    pwd = models.CharField(max_length=100)

    def __str__(self):
        return f"UserInfo：{self.uname}"

class Address(models.Model):
    aname = models.CharField(max_length=100)
    aphone = models.CharField(max_length=11)
    addr = models.CharField(max_length=200)
    isdefault = models.BooleanField(default=False)
    userinfo = models.ForeignKey(to="UserInfo", on_delete=models.CASCADE)

    def __str__(self):
        return f"Address：{self.aname}"


class ImprovePersonal(models.Model):
    uqqemail= models.CharField(max_length=20)
    uphone = models.CharField(max_length=11)
    ubirthday = models.DateField()
    usex = models.CharField(max_length=10)
    utag= models.CharField(max_length=200)
    user = models.ForeignKey(to="UserInfo", on_delete=models.CASCADE)

    def getUserName(self):
        return self.user.uname

    def getDefaultAddress(self):
        return Address.objects.filter(userinfo=self.user, isdefault=True).first()

templates/users/address.html
{% extends 'base.html' %}
{% load static %}
{% block title %}用户中心{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/mygxin.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link href="{% static 'css/../../static/load/assets/css/admin.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/personal.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/addstyle.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'css/../../static/load/assets/js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'css/../../static/load/assets/js/amazeui.js' %}"></script>
    <style>
        .person-info {
            /* 设置整个div的宽度、边距、内边距和背景色 */
            width: 100%; /* 或者指定一个具体的宽度，如300px */
            max-width: 600px; /* 最大宽度，以适应不同屏幕尺寸 */
            margin: 20px auto; /* 上下边距20px，左右自动居中 */
            padding: 20px; /* 内边距 */
            background-color: #f9f9f9; /* 浅灰色背景 */
            border-radius: 8px; /* 圆角边框 */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 阴影效果 */
            font-family: Arial, sans-serif; /* 字体设置 */
            color: #333; /* 字体颜色 */
        }

        .person-info p {
            /* 设置段落的样式 */
            margin-bottom: 10px; /* 段落下边距 */
            line-height: 1.6; /* 行高，使文字看起来更舒适 */
        }

        .person-info p span {
            /* 设置span（即标签名）的样式，使其右对齐 */
            display: inline-block;
            width: 80px; /* 标签名占据的宽度 */
            margin-right: 10px; /* 与值的间距 */
            text-align: right; /* 右对齐 */
            font-weight: bold; /* 加粗 */
        }
    </style>
{% endblock %}

{% block content %}
    {#  <input type="hidden" name="csrfmiddlewaretoken" value="SSm6OhZlgtgLmmLi07RWmPYijzLpebaCh0pFbf57zYddklUSB4EBEks157EvG81b">#}
    {% csrf_token %}
    <br>
    <div class="Bott">
        <div class="wrapper clearfix" style="margin: 0 auto">
            <div class="zuo fl" style="margin-left: 100px">
                <ul>
                    <li class="person active" style="border-bottom: #16b777 solid 5px;">
                        <a href="/users/center/"><i class="am-icon-user"></i>个人中心</a>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-newspaper-o"></i>个人资料</p>
                        <ul>
                            <li><a href="/users/center/">个人信息</a></li>
                            <li><a href="/users/editPersonal/">完善资料</a></li>
                            <li><a href="/users/address/" style="color: #16b777;">地址管理</a></li>
                            <li><a class="logout">退出登录</a></li>
                        </ul>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-balance-scale"></i>我的交易</p>
                        <ul>
                            <li><a href="/order/orderList/">订单管理</a></li>
                            <li><a href="/order/logistics/">物流管理</a></li>
                            <li><a href="/evaluate/my_comments/">我的评价</a></li>
                        </ul>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-balance-scale"></i>我的意见</p>
                        <ul>
                            <li><a href="/forum/consultation/">意见管理</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="you fl">
                <div class="user-address">
                    <!--标题 -->
                    <div class="am-cf am-padding">
                        <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">地址管理</strong> / <small>Address&nbsp;list</small>
                        </div>
                    </div>
                    <hr style="border:none;border-top:1px solid #16b777;">
                    <ul class="am-avg-sm-1 am-avg-md-3 am-thumbnails">
                        {% for address in address_list %}
                            <li class="user-addresslist {% if address.isdefault == 1 %}defaultAddr{% endif %}">
                                <span class="new-option-r"><i class="am-icon-check-circle"></i>默认地址</span>
                                <p class="new-tit new-p-re">
                                    <span class="new-txt">{{ address.aname }}</span>
                                    <span class="new-txt-rd2">{{ address.aphone }}</span>
                                </p>
                                <div class="new-mu_l2a new-p-re">
                                    <p class="new-mu_l2cw">
                                        <span class="title">地址：{{ address.addr }}</span>
                                </div>
                                <div class="new-addr-btn">
                                    <a href="/users/address/edit/{{ address.id }}"><i class="am-icon-edit"></i>编辑</a>
                                    <span class="new-addr-bar">|</span>
                                    <a href="/users/address/del/{{ address.id }}"><i class="am-icon-trash"></i>删除</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="clear"></div>
                    <a class="new-abtn-type" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0}">添加新地址</a>
                    <!--例子-->
                    <div class="" id="doc-modal-1">

                        <div class="add-dress">

                            <!--标题 -->
                            <div class="am-cf am-padding">
                                <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">新增地址</strong> /
                                    <small>Add&nbsp;address</small></div>
                            </div>
                            <hr style="border:none;border-top:1px solid #16b777;">

                            <div class="am-u-md-12 am-u-lg-8" style="margin-top: 20px;">
                                <form class="am-form am-form-horizontal" id='frm' method="post" action="/users/address/">
                                    {% csrf_token %}
                                    <div class="am-form-group">
                                        <label for="user-name" class="am-form-label">收货人</label>
                                        <div class="am-form-content">
                                            <input type="text" id="user-name" placeholder="收货人" name="aname">
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-phone" class="am-form-label">手机号码</label>
                                        <div class="am-form-content">
                                            <input id="user-phone" placeholder="手机号必填" type="email" name="aphone">
                                        </div>
                                    </div>
                                    <div class="am-form-group">
                                        <label for="user-address" class="am-form-label">所在地</label>
                                        <div class="am-form-content address">
                                            <select id="province" onchange="loadCity();">

                                            </select>
                                            <select id="city" onchange="loadTown();">

                                            </select>
                                            <select id="town">

                                            </select>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-intro" class="am-form-label">详细地址</label>
                                        <div class="am-form-content">
                                            <textarea name="addr" class="" rows="3" id="user-intro" onfocus="getAddr();"
                                                      placeholder="输入详细地址"></textarea>
                                            <small>100字以内写出你的详细地址...</small>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <div class="am-u-sm-9 am-u-sm-push-3">
                                            <a class="am-btn am-btn-danger" onclick="$('#frm').submit();" style="background-color:#16b777 ">保存</a>
                                            <a href="javascript: void(0)" class="am-close am-btn am-btn-danger"
                                               data-am-modal-close="" style="background-color:#16b777 ">取消</a>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>

                    </div>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".new-option-r").click(function () {
                $(this).parent('.user-addresslist').addClass("defaultAddr").siblings().removeClass("defaultAddr");
            });

            var $ww = $(window).width();
            if ($ww > 640) {
                $("#doc-modal-1").removeClass("am-modal am-modal-no-btn")
            }

        })
    </script>
    <script>
        $('.logout').click(function () {
            $.ajax({
                type: 'post',
                url: '/users/logout/',
                data: 'csrfmiddlewaretoken=' + $('input[name="csrfmiddlewaretoken"]').val(),
                success: function (result) { //result是返回的json数据,从views中返回的json数据
                    if (result.flag) {
                        window.location = '/users/login/'
                    }
                }
            })
        });
        $(function () {
            loadProvince();
        });

        function loadProvince() {
            loadArea('province', 0, loadCity);
        }

        function loadCity() {
            loadArea('city', $('#province').val(), loadTown);

        }

        function loadTown() {
            loadArea('town', $('#city').val());
        }

        //selectId:要加载的select的id,nextload:下一步要加载的函数
        // ,pid：数据库中parentid
        //json中的pk是数据库中的areaid
        //数据库中area表中parentid为0的为省份
        function loadArea(selectId, pid, nextload) {
            $.get('/users/loadArea/', {'pid': pid}, function (result) {
                console.log(result.area_list_json);
                {#alert(typeof(result.area_list_json) );#}
                var area_list = JSON.parse(result.area_list_json);

                //遍历
                for (let i = 0; i < area_list.length; i++) {
                    var area = area_list[i];
                    $('#' + selectId).append("<option value='" + area.pk + "'>" + area.fields.areaname + "</option>");

                }
                if (nextload != null) {
                    nextload();
                }
            });
        }
        function getAddr() {
            var province = $('#province option:selected').text();
            var city = $('#city option:selected').text();
            var town = $('#town option:selected').text();
            var addr = province + city + town + ',';
            $('#user-intro').text(addr);
        }
    </script>
    <script>
        layui.use(['upload', 'element', 'layer'], function () {
            var $ = layui.jquery
                , upload = layui.upload
                , element = layui.element
                , layer = layui.layer;

            //常规使用 - 普通图片上传
            var uploadInst = upload.render({
                elem: '#test1'
                , url: '/users/upload/' //此处用的是第三方的 http 请求演示，实际使用时改成您自己的上传接口即可。
                , before: function (obj) {
                    //预读本地文件示例，不支持ie8
                    obj.preview(function (index, file, result) {
                        $('#demo1').attr('src', result); //图片链接（base64）
                    });
                    element.progress('demo', '0%'); //进度条复位
                    layer.msg('上传中', {icon: 16, time: 0});
                }
                , done: function (res) {
                    //如果上传失败
                    if (res.code > 0) {
                        return layer.msg('上传失败');
                    }
                    //上传成功的一些操作
                    //……
                    $('#demoText').html(''); //置空上传失败的状态
                }
                , error: function () {
                    //演示失败状态，并实现重传
                    var demoText = $('#demoText');
                    demoText.html('<span style="color: #FF5722;">上传失败</span> <a class="layui-btn layui-btn-xs demo-reload">重试</a>');
                    demoText.find('.demo-reload').on('click', function () {
                        uploadInst.upload();
                    });
                }
            });
        });
    </script>
{% endblock %}

templates/users/address_edit.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/mygxin.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/public.css' %}">
    <link href="{% static 'css/../../static/load/assets/css/admin.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/amazeui.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/personal.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/../../static/load/assets/css/addstyle.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'css/../../static/load/assets/js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'css/../../static/load/assets/js/amazeui.js' %}"></script>
    <style>
        .person-info {
            /* 设置整个div的宽度、边距、内边距和背景色 */
            width: 100%; /* 或者指定一个具体的宽度，如300px */
            max-width: 600px; /* 最大宽度，以适应不同屏幕尺寸 */
            margin: 20px auto; /* 上下边距20px，左右自动居中 */
            padding: 20px; /* 内边距 */
            background-color: #f9f9f9; /* 浅灰色背景 */
            border-radius: 8px; /* 圆角边框 */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 阴影效果 */
            font-family: Arial, sans-serif; /* 字体设置 */
            color: #333; /* 字体颜色 */
        }

        .person-info p {
            /* 设置段落的样式 */
            margin-bottom: 10px; /* 段落下边距 */
            line-height: 1.6; /* 行高，使文字看起来更舒适 */
        }

        .person-info p span {
            /* 设置span（即标签名）的样式，使其右对齐 */
            display: inline-block;
            width: 80px; /* 标签名占据的宽度 */
            margin-right: 10px; /* 与值的间距 */
            text-align: right; /* 右对齐 */
            font-weight: bold; /* 加粗 */
        }
    </style>
{% endblock %}

{% block content %}
    {#  <input type="hidden" name="csrfmiddlewaretoken" value="SSm6OhZlgtgLmmLi07RWmPYijzLpebaCh0pFbf57zYddklUSB4EBEks157EvG81b">#}
    {% csrf_token %}
    <div class="Bott">
        <div class="wrapper clearfix" style="margin: 0 auto">
            <div class="zuo fl" style="margin-left: 100px">
                <ul>
                    <li class="person active" style="border-bottom: #16b777 solid 5px;">
                        <a href="/users/center/"><i class="am-icon-user"></i>个人中心</a>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-newspaper-o"></i>个人资料</p>
                        <ul>
                            <li><a href="/users/center/">个人信息</a></li>
                            <li><a href="/users/editPersonal/">完善资料</a></li>
                            <li><a href="/users/address/" style="color: #16b777;">地址管理</a></li>
                            <li><a class="logout">退出登录</a></li>
                        </ul>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-balance-scale"></i>我的交易</p>
                        <ul>
                            <li><a href="/order/orderList/">订单管理</a></li>
                            <li><a href="/order/logistics/">物流管理</a></li>
                            <li><a href="/evaluate/my_comments/">我的评价</a></li>
                        </ul>
                    </li>
                    <li class="person">
                        <p><i class="am-icon-balance-scale"></i>我的意见</p>
                        <ul>
                            <li><a href="/forum/consultation/">意见管理</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="main-wrap you fl">

                <div class="user-address">
                    <!--标题 -->
                    <div class="clear"></div>
                    <a class="new-abtn-type" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0}">编辑地址</a>
                    <!--例子-->
                    <div class="" id="doc-modal-1">

                        <div class="add-dress">

                            <!--标题 -->
                            <div class="am-cf am-padding">
                                <div class="am-fl am-cf"><strong class="am-text-danger am-text-lg">编辑地址</strong> /
                                    <small>Edit&nbsp;address</small></div>
                            </div>
                            <hr style="border:none;border-top:1px solid #16b777;">

                            <div class="am-u-md-12 am-u-lg-8" style="margin-top: 20px;">
                                <form class="am-form am-form-horizontal" id='frm' method="post" action="/users/address/">
                                    {% csrf_token %}
                                    <div class="am-form-group">
                                        <label for="user-name" class="am-form-label">收货人</label>
                                        <div class="am-form-content">
                                            <input type="text" id="user-name"  name="aname" value="{{ aname }}">
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-phone" class="am-form-label">手机号码</label>
                                        <div class="am-form-content">
                                            <input id="user-phone" value="{{ aphone }}" type="email" name="aphone">
                                        </div>
                                    </div>
                                    <div class="am-form-group">
                                        <label for="user-address" class="am-form-label">所在地</label>
                                        <div class="am-form-content address">
                                            <select id="province" onchange="loadCity();">

                                            </select>
                                            <select id="city" onchange="loadTown();">

                                            </select>
                                            <select id="town">

                                            </select>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <label for="user-intro" class="am-form-label" >详细地址</label>
                                        <div class="am-form-content">
                                            <textarea name="addr" class="" rows="3" id="user-intro" onfocus="getAddr();">{{ addr }}</textarea>
                                            <small>100字以内写出你的详细地址...</small>
                                        </div>
                                    </div>

                                    <div class="am-form-group">
                                        <div class="am-u-sm-9 am-u-sm-push-3">
                                            <a class="am-btn am-btn-danger update-address" >确定</a>
                                            <a href="javascript: void(0)" class="am-close am-btn am-btn-danger"
                                               data-am-modal-close="">取消</a>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>

                    </div>

                </div>

                <script type="text/javascript">
                    $(document).ready(function () {
                        $(".new-option-r").click(function () {
                            $(this).parent('.user-addresslist').addClass("defaultAddr").siblings().removeClass("defaultAddr");
                        });

                        var $ww = $(window).width();
                        if ($ww > 640) {
                            $("#doc-modal-1").removeClass("am-modal am-modal-no-btn")
                        }

                    })
                </script>

                <div class="clear"></div>

            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
    $('.logout').click(function () {
            $.ajax({
                type: 'post',
                url: '/users/logout/',
                data: 'csrfmiddlewaretoken=' + $('input[name="csrfmiddlewaretoken"]').val(),
                success: function (result) { //result是返回的json数据,从views中返回的json数据
                    if (result.flag) {
                        window.location = '/users/login/'
                    }
                }
            });
        });
        $(function () {
            loadProvince();
        });

        function loadProvince() {
            loadArea('province', 0, loadCity);
        }

        function loadCity() {
            loadArea('city', $('#province').val(), loadTown);

        }

        function loadTown() {
            loadArea('town', $('#city').val());
        }
        //selectId:要加载的select的id,nextload:下一步要加载的函数
        // ,pid：数据库中parentid
        //json中的pk是数据库中的areaid
        //数据库中area表中parentid为0的为省份
        function loadArea(selectId, pid, nextload) {
            $.get('/users/loadArea/', {'pid': pid}, function (result) {
                console.log(result.area_list_json);
                {#alert(typeof(result.area_list_json) );#}
                var area_list = JSON.parse(result.area_list_json);

                //遍历
                for (let i = 0; i < area_list.length; i++) {
                    var area = area_list[i];
                    $('#' + selectId).append("<option value='" + area.pk + "'>" + area.fields.areaname + "</option>");

                }
                if (nextload != null) {
                    nextload();
                }
            });
        }

        function getAddr() {
            var province = $('#province option:selected').text();
            var city = $('#city option:selected').text();
            var town = $('#town option:selected').text();
            var addr = province + city + town + ',';
            $('#user-intro').text(addr);
        }
         $('.update-address').click(function (event) {
            var username = $('#user-name').val();
            var phone = $('#user-phone').val();
            var addr = $('#user-intro').val();
            var csrfmiddlewaretoken = $('input[name="csrfmiddlewaretoken"]').val();
            var data = {
                aname: username,
                aphone: phone,
                addr: addr,
                csrfmiddlewaretoken: csrfmiddlewaretoken,
                type: 'update',
                id: {{ aid }}
            }
            $.ajax({
                type: 'post',
                url: '/users/address/edit/{{ aid }}/',
                data: data,
                success: function (result) {
                    if (result.flag) {
                        alert('修改成功');
                        window.location.href = '/users/address/';
                    } else {
                        alert('修改失败');
                    }
                }
            });
        });


    </script>
{% endblock %}

templates/users/service.html
{% extends 'base.html' %}
{% block title %}客服{% endblock %}
{% block style %}
    <style>
        .image-text-container {
            display: flex;
            flex-direction: column; /* 使得子元素垂直排列 */
            align-items: center; /* 水平居中 */
            justify-content: center; /* 垂直居中（在本例中对于单列布局主要是为了确保整个容器在其父元素中垂直居中） */
            text-align: center; /* 确保文本内容也水平居中 */
            width: 100%; /* 容器宽度 */
            max-width: 600px; /* 限制最大宽度，避免过宽 */
            margin: 0 auto; /* 在页面上水平居中 */
            padding: 20px; /* 内边距 */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* 添加一些阴影，使容器看起来更立体 */
        }

        .centered-image {
            width: 100%; /* 图片宽度自适应容器 */
            height: auto; /* 图片高度自适应 */
            max-width: 400px; /* 限制图片最大宽度 */
            margin-bottom: 10px; /* 图片下方留出空间给文字 */
        }

        .centered-text {
            /* 这里可以根据需要添加更多的样式，如字体大小、颜色等 */
            font-size: 16px; /* 示例字体大小 */
            color: #333; /* 示例文字颜色 */
        }
    </style>

{% endblock %}

{% block content %}
    <div class="image-text-container">
        <img src="/static/images/kefu.jpg" alt="客服" class="centered-image">
        <p class="centered-text" style="color:#16b777;">加客服微信，为你推荐更多内容!!</p>
    </div>
{% endblock %}

{% block script %}
{% endblock %}